// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {manejador} from '../models';

export function DevolverResultados(arg1:string,arg2:string,arg3:number):Promise<manejador.RespuestaGUI>;

export function DevolverSeleccionarCarpeta():Promise<string>;
